[project]
name = "llm-genai-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=1.18.0",
    "google-genai>=1.50.1",
    "pandas>=2.3.3",
    "pydantic>=2.12.4",
    "pydantic-settings>=2.12.0",
    "asyncpg>=0.30.0",
    "fastapi[all]>=0.118.0",
    "psycopg2-binary>=2.9.11",
    "sqlalchemy>=2.0.43",
]
